[build]
  publish = "public"
  command = "npm run build:netlify"

[functions]
  directory = "netlify-build/functions"
  node_bundler = "esbuild"

[functions.moras]
  timeout = 26

[dev]
  command = "npm run manse:web"
  port = 8888
  targetPort = 4173
